name: Docker Image CI

#maybe add branch filter
on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create a TimescaleDB docker instance
      run: docker run -d --name timescaledbci -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:latest-pg12

    - name: setup python
      uses: actions/setup-python@v4
      # with:
      #   python-version: 3.10 #install the python version needed

    - name: install necessary python modules
      run: pip install -r requirements.txt

    - name: setup test database with test data
      run: |
        python tests/setup_database.py

    # unit tests
    - name: tests the bin controller
      run: |
        python tests/unit_tests/test_bin_controller.py
