name: Docker Image CI

#maybe add branch filter
on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
    - uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm -g install serverless

    - name: Create a TimescaleDB docker instance
      run: docker run -d --name timescaledbci -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:latest-pg12

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11 #install the python version needed

    - name: install necessary python modules
      run: pip install -r requirements.txt

    - name: setup test database with test data
      run: |
        python tests/setup_database.py
    
    - name: for testing purposes
      run: |
        python tests/dummy_test_print.py

    # unit tests
    - name: tests the metrics controller
      run: |
        python tests/unit_tests/metrics_controller_tests.py

    - name: tests the bin controller
      run: |
        python tests/unit_tests/bin_controller_tests.py

    - name: build API for testing
      uses: serverless/github-action@v3.1
      with:
        args: offline
    
    - name: run endpoint tests
      run: |
        python tests/unit_tests/endpoint_testing.py
    
