name: Docker Image CI

#maybe add branch filter
on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create a TimescaleDB docker instance
      run: docker run -d --name timescaledbci -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:latest-pg12

    - name: Starting TimescaleDB docker instance
      run: sls offline

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python version needed

    - name: install necessary python modules
      run: pip install -r requirements.txt

    - name: setup test database with test data
      run: |
        python tests/setup_database.py

    - name: tests the bin endpoints
      run: |
        python tests/test_bin_endpoints.py
