name: deploy sls functions 

on:
  push:
    branches:
      - sls_deployment

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
       
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11 #install the python version needed
    # - name: change directory
    #   run: cd ./ZotbinsLambda

    - name: serverless deploy
      uses: serverless/github-action@3.1
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}